[".vim/pack/minpac/opt/minpac"]
    type = "git-repo"
    url = "https://github.com/k-takata/minpac.git"
    refreshPeriod = "168h"

{{- if eq .profile "work" }}
[".local/share/nvim/site/pack/paqs/start/paq-nvim"]
    type = "git-repo"
    url = "https://github.com/savq/paq-nvim.git"
    refreshPeriod = "168h"
{{- end }}
