#!/usr/bin/env bash

# Analyses the commit message using git-lint.

set -o nounset
set -o errexit
set -o pipefail
IFS=$'\n\t'

source "$HOME/.config/git/hooks/extensions/support.sh"
source "$HOME/.config/git/hooks/extensions/git.sh"

git_lint_analyze_commit
