" Move the viminfo file out of the $HOME directory.  A logical place would be
" $XDG_CACHE_HOME (typically $HOME/.cache/).
"
" This file will only be created if this directory exists, so this is handled
" during the installation of the dotfiles.
"
set viminfofile=$XDG_CACHE_HOME/vim/viminfo

" Enable file type detection.
" Also load indent files, to automatically do language-dependent indenting.
"
filetype plugin indent on

" Switch syntax highlighting on if it already not enabled.
"
if !exists('syntax_on')
  syntax on
endif
