tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Vi 'workalike' with many additional features
brew "vim"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Application uninstaller
cask "appcleaner"
