# Load ~/.profile regardless of shell.
if [ -e "$HOME"/.profile ]; then
  . "$HOME"/.profile
fi

# If ~/.bashrc exists, source that too.
if [ -f "$HOME"/.bashrc ]; then
  . "$HOME"/.bashrc
fi

# >>> coursier install directory >>>
export PATH="$PATH:/Users/dylan.pinn/Library/Application Support/Coursier/bin"
# <<< coursier install directory <<<
