name: CI

on: [push, pull_request]

jobs:
  lint-vim:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint Vim files
      run: ./lint-vim.sh

  lint-shell:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Lint Shell files
      run: ./lint-shell.sh

